In [1]:
import tensorflow as tf


/home/o/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a=tf.ones([2,3])

In [3]:
a

<tf.Tensor: id=2, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
a.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [5]:
a=tf.zeros([3,3])

In [6]:
a

<tf.Tensor: id=6, shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [7]:
a=tf.random.normal([3,3], mean=1, stddev=1)

In [33]:
import tensorflow.keras.layers as layers

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras import backend as k
from tensorflow.keras import losses
import numpy as np
import tensorflow as tf
from sklearn.metrics import mean_squared_error
from math import sqrt

model = Sequential()
model.add(Dense(12, input_dim=8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

inputs = np.random.random((1, 8))
outputs = model.predict(inputs)
targets = np.random.random((1, 8))
rmse = sqrt(mean_squared_error(targets, outputs))
loss = losses.mean_squared_error(targets, model.output)

#  ===== Symbolic Gradient =====
with tf.GradientTapedi() as tape:
    
gradients = k.gradients(loss, model.trainable_weights)

print("===BEFORE WALKING DOWN GRADIENT===")
print("outputs:\n", outputs)
print("targets:\n", targets)

# Begin TensorFlow
sess = tf.InteractiveSession()
sess.run(tf.initialize_all_variables())

steps = 100  # steps of gradient descent
for s in range(steps):

    # ===== Numerical gradient =====
    evaluated_gradients = sess.run(gradients, feed_dict={model.input: inputs})

    # Step down the gradient for each layer
    for i in range(len(model.trainable_weights)):
        sess.run(tf.assign_sub(model.trainable_weights[i], evaluated_gradients[i]))

    # Every 10 steps print the RMSE
    if s % 10 == 0:
        outputs = model.predict(inputs)
        rmse = sqrt(mean_squared_error(targets, outputs))
        print("step " + str(s) + " rmse:", rmse)

final_outputs = model.predict(inputs)
final_rmse = sqrt(mean_squared_error(targets, final_outputs))

print("===AFTER STEPPING DOWN GRADIENT===")
print("outputs:\n", outputs)
print("targets:\n", targets)

RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

In [36]:
x=tf.random.normal([4,3,28,28])

In [37]:
x.shape

TensorShape([4, 3, 28, 28])

In [39]:
tf.transpose(x,[0,2,3,1]).shape

TensorShape([4, 28, 28, 3])

In [42]:
tf.expand_dims(x,-1).shape

TensorShape([4, 3, 28, 28, 1])

In [43]:
a=tf.ones([1])

In [44]:
b=tf.Variable(a)

In [45]:
b


<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>

In [46]:
b.trainable

True

In [47]:
b.value

<bound method ResourceVariable.value of <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>>

In [48]:
from tensorflow import keras


In [49]:
net=keras.Sequential([keras.layers.Dense(10)])

In [50]:
net

In [51]:
net.trainable_variables

[]

In [54]:
net.build(input_shape=[None, 20])


In [55]:
net

In [59]:
len(net.layers)

1

In [60]:
inp=tf.random.normal([4,20])

In [61]:
out=net(inp)

In [62]:
out.shape


TensorShape([4, 10])

In [63]:
with tf.GradientTape() as tape:
    out = net(inp)


In [67]:
res=net.layers[0]

In [71]:
a=tf.constant([2,3])

In [72]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [69]:
res.bias.trainable

True

In [9]:
a.ndim


2

In [10]:
a.dtype


tf.float32

In [11]:
a.get_shape()

TensorShape([3, 3])

In [12]:
a.shape[0]


3

In [13]:
tf.cast(a,tf.int32)

<tf.Tensor: id=15, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=int32)>

In [14]:
tf.cast(a, tf.int16)

<tf.Tensor: id=17, shape=(3, 3), dtype=int16, numpy=
array([[0, 1, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=int16)>

In [15]:
tf.cast(a,tf.int)

AttributeError: module 'tensorflow' has no attribute 'int'

In [ ]:
tf.cast(a, tf.int64)

In [ ]:
a

In [18]:
a=tf.random.uniform([2,3])



In [19]:
a


<tf.Tensor: id=25, shape=(2, 3), dtype=float32, numpy=
array([[0.82849145, 0.3901372 , 0.3483795 ],
       [0.27646065, 0.7812692 , 0.16053963]], dtype=float32)>

In [20]:
b=a*2


In [21]:
id(b),id(a)

(140379071730408, 140383013058936)

In [22]:
tf.cast(b,tf.int32)

<tf.Tensor: id=29, shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0]], dtype=int32)>

In [23]:
b.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [24]:
x=tf.ones([2,2])

In [28]:
x = tf.random.normal(2)
# with tf.GradientTape() as tape:
    

InvalidArgumentError: shape must be a vector of {int32,int64}, got shape [] [Op:RandomStandardNormal]

In [29]:
x=tf.ones([2,1,3])

In [30]:
x

<tf.Tensor: id=44, shape=(2, 1, 3), dtype=float32, numpy=
array([[[1., 1., 1.]],

       [[1., 1., 1.]]], dtype=float32)>

In [31]:
tf.squeeze(x, axis=1)

<tf.Tensor: id=46, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.

In [27]:
x

<tf.Tensor: id=37, shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>